# Generated by Django 2.2.7 on 2019-11-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='people',
            name='birthday',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='deathday',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='en_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='people',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='people',
            name='ko_name',
            field=models.CharField(max_length=300),
        ),
    ]
