# Generated by Django 2.2.7 on 2019-11-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ko_name', models.CharField(max_length=30)),
                ('en_name', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('is_alive', models.BooleanField()),
                ('popularity', models.FloatField()),
                ('place_of_birth', models.TextField(null=True)),
                ('img_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField(null=True)),
                ('release_date', models.CharField(max_length=30)),
                ('img_url', models.TextField(null=True)),
                ('country', models.CharField(max_length=50)),
                ('rating', models.FloatField()),
                ('popularity', models.FloatField()),
                ('actors', models.ManyToManyField(related_name='actor_movies', to='movies.People')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.People')),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
